# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# vice by Thomas Leon Highbaugh thighbaugh@zoho.com

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#17191E"
idle_fg = "#8b9cbe"
info_bg = "#8265ff"
info_fg = "#17191E"
good_bg = "#0badff"
good_fg = "#17191E"
warning_bg = "#f0ffaa"
warning_fg = "#17191E"
critical_bg = "#ff87d7"
critical_fg = "#17191E"
# The rest of the theme settings are left at default.
